radio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib import admin
admin.autodiscover()


urlpatterns = [


    url(r'^comanda/$', 'radio.views.comanda', name='comanda'),
    url(r'^tariffs/$', 'radio.views.tariffs', name='tariffs'),
    url(r'^payment/$', 'radio.views.payment', name='payment'),
    url(r'^connect/$', 'radio.views.connect', name='connect'),
    url(r'^contacts/$', 'radio.views.contacts', name='contacts'),
    url(r'^callback/$', 'radio.views.callback', name='callback'),
    url(r'^contacts/thanks/$', 'radio.views.callback', name='thanks'),
    url(r'^fotogalerys/get/(?P<item_id>\d+)/$', 'radio.views.fotogalery', name='fotogalery'),
    url(r'^services/get/(?P<service_id>\d+)/$', 'radio.views.service', name='service'),
    url(r'^newss/get/(?P<news_id>\d+)/$', 'radio.views.news', name='news'),
    url(r'^page/(\d+)/$', 'radio.views.newss', name='newss'),

    url(r'^fotogalerys/$', 'radio.views.fotogalerys', name='fotogalerys'),
    url(r'^services/$', 'radio.views.services', name='services'),
    url(r'^$', 'radio.views.newss', name='newss'),
    #url(r'^$', 'radio.views.callback', name='callback'),


    ]

radioservice/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('radio.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

radio/forms.py
# -*- coding: utf-8 -*-


from django import forms


# Модель формы обратной связи
'''class ContactForm(forms.Form):
    name = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'size':'100','class': 'form-control'}))
    message = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'size': '100', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'size':'100','class': 'form-control'}))
    #message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.CharField(required=False)'''


class ContactForm(forms.Form):
    name = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'size':'100','class': 'form-control'}))
    phon = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'size':'100','class': 'form-control'}))
    message = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'size': '100', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'size':'100','class': 'form-control'}))
    #message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.CharField(required=False)

templates/callback.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block callback %}

        <div class="col-sm-12">
            <form action="/callback/" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                    <div class="form-group">
                        <label  for="id_name">№ Договору:</label>
                        <input type="text" name="name" class="form-control" id="name" value="{{ name }}" placeholder="Введіть номер Вашого договору" required/>
                    </div>
                    <div class="form-group">
                        <label for="id_message">Ваше повідомлення:</label>
                        <input type="text" name="message" class="form-control" id="message" value="{{ message }}" placeholder="Вкажіть номер телефону свій email та свое повідомлення:" required/>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Ваш емейл:</label>
                        <input type="text" name="email" class="form-control" id="email" value="{{ email }}" placeholder="Введіть Ваш email" required/>
                        {% if errors %}
                        <ul>
                            {% for error in errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                  <input class="btr btn-success" type="submit" value="Відправити">
            </form>
        </div>


                <!--<div class="col-sm-12">
                    <form action="/callback/" method="post">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                           <h2>Замовити зворотній звязок</h2>
                            <div class="form-group row">
                                    <label class="col-sm-5 col-form-label" for="id_name">№ Договору:</label>
                                    <div class="col-sm-6">
                                            <input type="text" name="name" value="{{ name }}" placeholder="Ваш договір" required/>
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label class="col-sm-5 col-form-label" for="id_phon">Ваше повідомлення:</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="message" value="{{ message }}" placeholder="Ваше повідомлення" required/>
                                    </div>
                            </div>

                             <div class="form-group row">
                                    <label class="col-sm-5 col-form-label" for="id_email">Ваш email:</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="email" value="{{ email }}" placeholder="Ваш емейл" required/>
                                        {% if errors %}
                                            <ul>
                                                {% for error in errors %}
                                                <li>{{ error }}</li>
                                                {% endfor %}
                                            </ul>
                                        {% endif %}
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label class="col-sm-5 col-form-label" for="id_message">Повідомлення:</label>
                                    <div class="col-sm-6">
                                        {{ form.message }}
                                        {{ form.message.errors }}
                                        <input id="id_message" type="text" name="text" placeholder="Ваше повідомлення" required/>
                                    </div>
                            </div>

                        <div class="col-sm-4"></div>
                        <div class="col-sm-4">
                            <input class="btr btn-success" type="submit" value="Відправити">
                        </div>
                        <div class="col-sm-4"></div>
                    </form>
                </div>-->

{% endblock %}

templates/central.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block central %}

<section class="container marketing">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 blog-main">
<!--<img alt="Інтернет у Львові та Львівській області" src="/images/main.png" /> -->
                    <div class="col-sm-8 blog-main">
                        {% block newss %}{% endblock %}
                        {% block services %}{% endblock %}
                        {% block tariffs %}{% endblock %}
                        {% block payment %}{% endblock %}
                        {% block connect %}{% endblock %}
                        {% block contacts %}{% endblock %}
                    </div>

                    <div class="col-sm-4">
                         <div class="sidebar-module">
                            <h2 class="text-center">"Радіо Сервіс"</h2>
                            <div class="text-center">
                                <a class="btn btn-success" href="#" role="button">Facebook</a>
                                <a class="btn btn-success" href="/comanda/" role="button">Команда Радіосервіс</a>
                                <!--<a class="btn btn-success" href="#" role="button">VK</a>-->
                            </div>

                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- /.container -->
{% endblock %}

templates/comanda.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block comanda %}

<!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

<!-- <div class="col-sm-12 text-center">

  <h1>Дирекція фірми</h1>
  <hr>


        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/tishin.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>Директор фірми</h5>
          <h4>Тишин Володимир</h4>
        </div><!-- /.col-lg-4 -->
        <!-- <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h5>Технічний деректор</h5>
          <h4>Кабин Руслан</h4>
        </div><!-- /.col-lg-4 -->
        <!-- <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h5>Фінансовий деректор</h5>
          <h4>Куса Уляна</h4>
        </div><!-- /.col-lg-4 -->
<!--</div> -->

<div class="col-sm-12 text-center">

  <h1>Офіс</h1>
  <hr>


        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/ivanov.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>Менеджер</h5>
          <h4>Іванов Ігор</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/yarish.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>Менеджер</h5>
          <h4>Яріш Надія</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/Olena.JPG" alt="Generic placeholder image" width="140" height="140">
          <h5>Менеджер</h5>
          <h4>Коваль Олена</h4>
        </div><!-- /.col-lg-4 -->
</div>

<div class="col-sm-12 text-center">

  <h1>Адміністратори мережі</h1>
  <hr>


        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/login.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Логін Віталій</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/stepanuk.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Степанюк Василь</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/iam.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Петровський Олександр</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/peleh.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Пелех Олег</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/krichko.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Кричко дмитро</h4>
        </div><!-- /.col-lg-4 -->
</div>

<div class="col-sm-12 text-center">

  <h1>Монтажний відділ</h1>
  <hr>


        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/pavlyk.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>Провідний інженер</h5>
          <h4>Павлик Ярослав</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/lencik.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Ленцик Володимир</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Бабич Роман</h4>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="/static/images/comanda/kulf.jpg" alt="Generic placeholder image" width="140" height="140">
          <h5>інженер</h5>
          <h4>Вільчинський Андрій</h4>
        </div><!-- /.col-lg-4 -->
</div>
{% endblock %}

templates/connect.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block connect %}

<div class="col-sm-12 text-center">

		<h1>Визначення технічної можливості</h1>
		<hr>
		<p>
			Ми здійснюємо підключення до мережі Інтернет по радіоканалу.
			Для цього встановлюється спеціальна антена, спрямована на одну з наших
			базових станцій. Для забезпечення якісного зв'язку, підключення можливе
			при прямій видимості на базову санцію.
		</p>
		<p>
			Наш спеціаліст на місці визначить рівень і якість сигналу, місце для
			кріплення антени та необхідну довжину кабеля (від антени до комп'ютера).
			Ці показники впливають на вартість підключення.
		</p>
		<h2>
			<!-- Заповніть, будь ласка, форму, щоб ми могли сконтактувати з вами, <br>або --> Для замовлення підключення зателефонуйте за номером телефону:<b>(067) 67 127 00</b>.
		</h2>

		<!--<div id="connect-request">
			<form action="/requests/connect" method="post">
								<div id="no-location-warning" class="warning-message">
					Вашої адреси не знайдено на карті, виберіть її, будь-ласка, вручну.
					Пересуньте маркер на карті у потрібну точку.
				</div>
				<div id="form-invalid-warning" class="warning-message">
					Поля позначені червоним кольором сигналізують про неправильність даних.
					Як тільки дані будуть правильними, червоний колір зникне. <br />
					Поля позначені зірочкою обов'язкові для заповнення.
				</div>
				 <div id="map-container">
					<div id="map_canvas"></div>

					<span class="fieldset">
						<span class="input-line">
							<label class="label-big required" for="input-ka">Широта</label>
							<input id="input-ka" type="text" name="ka" />
							<input id="input-ka-real" type="hidden" name="ka_real" />
						</span>

						<span class="input-line">
							<label class="label-big required" for="input-la">Довгота</label>
							<input id="input-la" type="text" name="la" />
							<input id="input-la-real" type="hidden" name="la_real" />
						</span>
					</span>

				</div>
				<div id="request-form">

					<span class="fieldset">
						<span class="input-line">
							<label class="label-big required" for="input-city">Адреса</label>
							<span>
								<input id="input-city" class="input-not-empty" type="text" name="city" value="" />
								<label class="label-small" for="input-city">Населений пункт (наприклад, Львів)</label>
							</span>
						</span>

						<span class="input-line">
							<span>
								<input id="input-street" class="input-not-empty" type="text" name="street" value="" />
								<label class="label-small" for="input-street">Вулиця (наприклад, вул. Шевченка)</label>
							</span>

							<span>
								<input id="input-number" class="input-not-empty" type="text" name="number" value="" />
								<label class="label-small" for="input-number">Номер будинку</label>
							</span>
						</span>

					</span>
					<span class="fieldset">
						<span class="input-line">
							<label class="label-big required" for="input-contact">Контактна особа</label>
							<span>
								<input id="input-contact" class="input-not-empty" type="text" name="contact" value="" />
								<label class="label-small" for="input-contact">(наприклад, Олег або Коваль Сергій)</label>
							</span>
						</span>

						<span class="input-line">
							<label class="label-big required" for="input-phone">Телефон</label>
							<span>
								<input id="input-phone" class="input-telephone" type="text" name="phone" value="" />
								<label class="label-small" for="input-phone">(наприклад, +38 (032) 230-00-00)</label>
							</span>
						</span>

						<span class="input-line">
							<label class="label-big" for="input-email">Електронна пошта</label>
							<span>
								<input id="input-email" class="input-email input-optional" type="text" name="email" value="" />
								<label class="label-small" for="input-email">(наприклад, someone@example.com)</label>
							</span>
						</span>
					</span>
					<span class="fieldset">
						<label class="label-big" for="input-notes">Примітки</label>
						<textarea id="input-notes" class="input-all input-optional" name="notes"></textarea>
						<label class="label-small" for="input-notes">(наприклад, дзвоніть після 14:00)</label>
					</span>
				</div>
			</form>
		</div>-->
		<hr>

		<h2>Оплата згідно рахунку</h2>
		<hr>
		<p>
			Вартість підключення визначається спеціалістом і залежить від необхідної довжини
			кабелю, якості сигналу, місця кріплення антени, тощо.
		</p>
		<hr>
		<h2>Монтаж та підписання договору</h2>
		<hr>
		<p>
			Монтаж відбувається протягом кількох днів з моменту надходження коштів.
			Після монтажу укладається договір про надання телекомунікаційних послуг.
		</p>

</div>


{% endblock %}

templates/fotogalery.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block fotogalerys %}

<div class="col-sm-12 text-center">
	<h1 class="text-center"><a href="{% url 'fotogalerys' %}">{{ item.name }}</a></p></th></h1>
	<hr>
</div>

    {% for photo in photos %}
		<div class="col-sm-4 text-center">
			<table class="gallery table table-bordered table-hover text-center">
				<thead>
					<tr class="success text-center">
					  <th class="text-center">{{ photo.photo_title }}</th>
					</tr>
				</thead>
				  <tbody>
					<tr class="success">
						<td>
							<img class="thumbnail" src="{{ MEDIA_URL }}{{ photo.photo_image.url }}" alt="Фото" />
						</td>
					</tr>
				  </tbody>

			</table>
		</div>
    {% endfor %}
{% endblock %}

templates/fotogalerys.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block fotogalerys %}

<div class="col-sm-12 text-center">

	<h1>Фотогалерея компанії РадіоСервіс</h1>
	<hr>
    {% for item in items %}
    <div class="col-sm-4 text-center">
    	<table class="table table-striped text-center">
			<thead>
				<tr class="success">
					<th class="text-center"><p><a href="/fotogalerys/get/{{ item.id }}/">{{ item.name }}</a></p></th>
				</tr>
			</thead>
			<tbody>
				<tr class="success">
					<td>
						{% if item.image %}
                        <p><a href="/fotogalerys/get/{{ item.id }}/"><img class="thumbnail" src="{{ MEDIA_URL }}{{ item.image.url }}" width="200" height="150" alt="Радіо Сервіс" /></a></p>
						{% else %}
						<p><a href="/fotogalerys/get/{{ item.id }}/"><img class="thumbnail" src="/static/images/logotip.png" width="200" height="150" alt="Радіо Сервіс" /></a></p>
                        {% endif %}
					</td>
				</tr>
			</tbody>
	    </table>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/news.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load embed_video_tags %}


{% block newss %}


            <div class="col-sm-5">
                {% if news.news_image %}
                    <img src="{{ MEDIA_URL }}{{ news.news_image.url }}" width="250" height="200"  />
                {% else %}
                    <img src="/static/images/radioservice.jpg" width="250" height="200" alt="Радіо Сервіс" />
                {% endif %}
            </div>

            <div class="col-sm-7">
                <h3 class="text-center"><a href="{% url 'newss' %}">{{ news.news_title }}</a></h3>
                <hr>
                <p>{% autoescape off %}{{ news.news_text }}{% endautoescape off %}</p>
                {% if news.video %}
                    <iframe width="560" height="315" src="{{ product.product_video }}" frameborder="0" allowfullscreen></iframe>
                {% endif %}

            </div>

{% endblock %}

templates/newss.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block newss %}

    <h1 class="text-center">Останні новини</h1>
    <hr>

        {% for news in newss %}
                    <div class="col-sm-12">
                        <div class="col-sm-3">
                            <h5>{{ news.news_date }}</h5>
                        </div>
                        <div class="col-sm-3">
                            {% if news.news_image %}
                                <p><a href="/newss/get/{{ news.id }}/"><img class="thumbnail" src="{{ MEDIA_URL }}{{ news.news_image.url }}" width="150" height="100" /></a></p>
                            {% else %}
                                <p><a href="/newss/get/{{ news.id }}/"><img class="thumbnail" src="/static/images/emblema.png" width="150" height="100" /></a></p>
                            {% endif %}
                        </div>
                        <div class="col-sm-6">
                            <h4>{{ news.news_title }}</h4>
                            <a class="btn btn-success" href="/newss/get/{{ news.id }}/" role="button">Дізнатися більше</a>
                            <hr>
                        </div>
                    </div>
        {% endfor %}

                      <div class="col-sm-12 text-center">
                          <ul class="pagination">
                              {% if newss.has_previous %}
                                    <li class="page-link"><a href="/page/{{ newss.previous_page_number }}/">&laquo;</a></li>
                              {% else %}
                                    <li class="page-item disabled"><a href="#">&laquo;</a></li>
                              {% endif %}
                              {% for page in newss.paginator.page_range %}
                                {% if page == newss.number %}
                                    <li class="page-item active"><a href="/page/{{ page }}/">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="/page/{{ page }}/" aria-label="{{ page }}">{{ page }}</a></li>
                                {% endif %}
                              {% endfor %}
                              {% if newss.has_next %}
                                    <li class="page-link"><a href="/page/{{ newss.next_page_number }}/" aria-label="Next page">&raquo;</a></li>
                              {% else %}
                                    <li class="page-item disabled"><a href="#">&raquo;</a></li>
                              {% endif %}
                          </ul>
                      </div>



{% endblock %}

templates/payment.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block payment %}
<div class="col-sm-12 text-center">
    <h1>СПОРСОБИ ОПЛАТИ ЗА НАДАННЯ ПОСЛУГ</h1>
    <hr>
    <div class="col-sm-12 text-center">
        <div class="col-sm-7 text-center">
            <h2>Оплата в терміналах Easypay</h2>
            <hr>
            <p>Здійснити оплату за надання послуг можливо в платіжних терміналах Easypay, або онлайн на сайті Easypay.ua.</p>
            <p>Для здійснення оплатити онлайн натисніть:</p>
            <a class="btn btn-success" href="https://easypay.ua/internet-tv/radio-service" role="button">Оплатити онлайн Easypa.ua</a>
        </div>
        <div class="col-sm-3">
            <p><a href="https://easypay.ua/internet-tv/radio-service"><img src="/static/images/easypay.png" width="300" height="200" alt="Easypay"/></a></p>
        </div>
    </div>

    <h5>1</h5>
    <hr>

    <div class="col-sm-12 text-center">
        <div class="col-sm-7 text-center">
            <h2>Оплата в банках ПАТ "КредоБанк"</h2>
            <hr>
            <p>Касиру вказати отримувача (Радіо Сервіс) та номер угоди.</p>
            <p>Дізнатися філії та відділення КредоБанку натисніть:</p>
            <a class="btn btn-success" href="http://www.kredobank.com.ua/our_coordinates.html" role="button">Філії та відділення КредоБанку</a>
        </div>
        <div class="col-sm-3">
            <p><a href="http://www.kredobank.com.ua/our_coordinates.html"><img src="/static/images/kredobank.jpg" width="300" height="200" alt="kredobank"/></a></p>
        </div>
    </div>

    <h5>2</h5>
    <hr>

    <div class="col-sm-12 text-center">
        <div class="col-sm-7 text-center">
            <h2>Оплата в банках ПриватБанк</h2>
            <hr>
             <ol>
                <li>Всі послуги</li>
                <li>Комуналка</li>
                <li>Оплата заборгованості</li>
                <li>Інтернет</li>
                <li><em>Вибрати область та місто, вказати адресу</em></li>
                <li><em>Вибрати зі списку <strong>ТзОВ ВКФ "Радіо Сервіс", Лімітед</strong></em></li>
                <li><em>Вказати номер угоди</em></li>
                <li><em>Далі згідно підказок...</em></li>
             </ol>
            <a class="btn btn-success" href="https://my-payments.privatbank.ua/mypayments/customauth/identification/fp/static?staticToken=23198536-51d2-4387-b42b-18a13c98" role="button">Оплатити онлайн ПриватБанк</a>
        </div>
        <div class="col-sm-3">
            <p><a href="https://my-payments.privatbank.ua/mypayments/customauth/identification/fp/static?staticToken=23198536-51d2-4387-b42b-18a13c98"><img src="/static/images/privat24.png" width="300" height="200" alt="privat24"/></a></p>
        </div>
    </div>

    <h5>3</h5>
    <hr>

     <div class="col-sm-12 text-center">
        <div class="col-sm-7 text-center">
            <h2>Оплата в інших банках</h2>
            <hr>
            <table class="table table-striped text-center"
			  <tbody>
				<tr>
				  <td class="success">Отримувач</td>
				  <td>ТзОВ ВКФ "Радіо Cервіс", Лімітед<br>ЄДРПОУ 13825541<br>Р/р 2600501098896 у ЦФ ПАТ "КредоБанк" МФО 325365</td>
				</tr>
				<tr>
				  <td class="success">Призначення платежу</td>
				  <td>Телекомунікаційні послуги</td>
				</tr>
				<tr>
				  <td class="success">Платник</td>
				  <td>Номер угоди, П.І.Б. власника угоди</td>
				</tr>
			  </tbody>
	        </table>
        </div>
        <div class="col-sm-3">
            <p><a href="#"><img src="/static/images/athepay.jpg" width="300" height="200" alt="athepay"/></a></p>
        </div>
     </div>

    <h5>4</h5>
</div>

{% endblock %}

templates/service.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load embed_video_tags %}


{% block services %}


            <div class="col-sm-5">
                {% if service.service_image %}
                    <img src="{{ MEDIA_URL }}{{ service.service_image.url }}" width="250" height="200"  />
                {% else %}
                    <img src="/static/images/radioservice.jpg" width="250" height="200" alt="Радіо Сервіс" />
                {% endif %}
            </div>

            <div class="col-sm-7">
                <h3 class="text-center"><a href="{% url 'services' %}">{{ service.service_title }}</a></h3>
                <hr>
                <p>{% autoescape off %}{{ service.service_text }}{% endautoescape off %}</p>
                {% if services.video %}
                    <iframe width="560" height="315" src="{{ service.service_video }}" frameborder="0" allowfullscreen></iframe>
                {% endif %}

            </div>

{% endblock %}

templates/services.html
{% extends 'index.html' %}
{% load staticfiles %}


{% block services %}

    <h1 class="text-center">Сервіси, що надаються фірмою</h1>
    <hr>
       {% for service in services %}
            <div class="col-sm-12">
                        <div class="col-sm-5">
                            {% if service.service_image %}
                            <p><a href="/services/get/{{ service.id }}/"><img class="thumbnail" src="{{ MEDIA_URL }}{{ service.service_image.url }}" width="200" height="150"/></a></p>
                            {% else %}
                            <img src="/static/images/emblema.png" width="250" height="200" alt="Радіо Сервіс" />
                            {% endif %}
                        </div>

                        <div class="col-sm-7 text-center">
                            <h3>{{ service.service_title }}</h3>
                            <a class="btn btn-success" href="/services/get/{{ service.id }}/" role="button">Дізнатися більше</a>
                            <hr>
                        </div>
            </div>
        {% endfor %}
{% endblock %}

templates/thanks.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block callback %}
    <div class="col-sm-12 text-center">
        <h1>Ваш лист успішно відправлений на почтову скриньку компанії РадіоСервіс лімітед!</h1>
        <hr>
        <h1>Дякуемо за Вашу турботу!</h1>
    </div>

{% endblock %}